fix: workflows

diff --git a/.github/workflows/1 - feature.yml b/.github/workflows/1 - feature.yml
--- a/.github/workflows/1 - feature.yml
+++ b/.github/workflows/1 - feature.yml
@@ -3,6 +3,7 @@ on:
   push:
     branches:
       - 'feature/*'
+
 jobs:
   build-and-test:
     runs-on: ubuntu-latest
@@ -26,9 +27,12 @@ jobs:
         run: |
           cd tests
           make coverage
-          coverage_percentage=$(gcovr -r . | grep 'TOTAL' | awk '{print $5}' | sed 's/%//')
+          coverage_percentage=$(gcovr -r .. | grep 'TOTAL' | awk '{print $4}' | sed 's/%//')
           echo "Code coverage: $coverage_percentage%"
-          if (( $(echo "$coverage_percentage >= 80" | bc -l) )); then
+          if [ -z "$coverage_percentage" ]; then
+            echo -e "\033[0;31mFailed to calculate code coverage\033[0m"
+            exit 1
+          elif (( $(echo "$coverage_percentage >= 80" | bc -l) )); then
             echo -e "\033[0;32mCode coverage is above 80% ($coverage_percentage%)\033[0m"
           else
             echo -e "\033[0;31mCode coverage is below 80% ($coverage_percentage%)\033[0m"
